# Generated by Django 5.2 on 2026-02-18 22:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(choices=[('booking_inquiry', 'استفسار حجز'), ('sports_club', 'النادي الرياضي'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح'), ('other', 'أخرى')], max_length=100, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_replied', models.BooleanField(default=False, verbose_name='تم الرد')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('reply_message', models.TextField(blank=True, verbose_name='نص الرد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('code', models.CharField(blank=True, max_length=3, verbose_name='الكود')),
            ],
            options={
                'verbose_name': 'جنسية',
                'verbose_name_plural': 'الجنسيات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='الصورة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('working_hours', models.CharField(max_length=100, verbose_name='ساعات العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الحجز')),
                ('arrival_date', models.DateField(verbose_name='تاريخ الوصول')),
                ('departure_date', models.DateField(verbose_name='تاريخ المغادرة')),
                ('number_of_adults', models.PositiveIntegerField(default=1, verbose_name='عدد البالغين')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='عدد الأطفال')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='طلبات خاصة')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(default='confirmed', max_length=20, verbose_name='الحالة')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='إجمالي السعر')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pages.nationality', verbose_name='الجنسية')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='البريد المستلم')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pages.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'كاش'), ('credit_card', 'بطاقة ائتمان'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='رقم العملية')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='pages.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'دفع',
                'verbose_name_plural': 'المدفوعات',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر لليلة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('total_rooms', models.PositiveIntegerField(default=1, verbose_name='إجمالي عدد الغرف')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='السعة (عدد الأشخاص)')),
                ('bed_type', models.CharField(max_length=100, verbose_name='نوع السرير')),
                ('size', models.CharField(help_text='مثال: 30 م²', max_length=100, verbose_name='المساحة')),
                ('flag', models.CharField(choices=[('available', 'متاحة'), ('not_available', 'غير متاحة'), ('vip', 'VIP'), ('most_requested', 'الأكثر طلباً')], default='available', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flag'], name='pages_room_flag_918a7d_idx'), models.Index(fields=['price'], name='pages_room_price_885b86_idx'), models.Index(fields=['is_active'], name='pages_room_is_acti_c754ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='pages.booking', verbose_name='الحجز')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pages.room', verbose_name='الغرفة'),
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class', max_length=50, verbose_name='الأيقونة')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='pages.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'ميزة الغرفة',
                'verbose_name_plural': 'ميزات الغرف',
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('available_count', models.PositiveIntegerField(verbose_name='العدد المتاح')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر مخصص')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='pages.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'توافر الغرفة',
                'verbose_name_plural': 'توافر الغرف',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'صورة غرفة',
                'verbose_name_plural': 'صور الغرف',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الحجز')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='الموعد المحدد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر وقت الحجز')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='pages.booking', verbose_name='الحجز')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pages.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'حجز خدمة',
                'verbose_name_plural': 'حجوزات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التفصيل')),
                ('description', models.TextField(blank=True, verbose_name='وصف إضافي')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'تفصيل الخدمة',
                'verbose_name_plural': 'تفاصيل الخدمات',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='pages_booki_booking_2ec0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['arrival_date', 'departure_date'], name='pages_booki_arrival_eeb80e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['email'], name='pages_booki_email_f69756_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomamenity',
            unique_together={('room', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='roomavailability',
            unique_together={('room', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='servicedetail',
            unique_together={('service', 'name')},
        ),
    ]
