# Generated by Django 5.2 on 2026-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, default='club/default.jpg', null=True, upload_to='club/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='workingoaches',
            name='image',
            field=models.ImageField(blank=True, default='workingoaches/default.jpg', null=True, upload_to='workingoaches/', verbose_name='الصورة'),
        ),
    ]
