# Generated by Django 5.2 on 2026-02-28 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_membershipplans_membershipplanfeatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_types/', verbose_name='الصورة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('flag', models.CharField(choices=[('available', 'متاحة'), ('not_available', 'غير متاحة'), ('vip', 'VIP'), ('most_requested', 'الأكثر طلباً')], default='available', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع المرفق',
                'verbose_name_plural': 'أنواع المرافق',
            },
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'مجموعة', 'verbose_name_plural': 'المجموعات'},
        ),
        migrations.AlterModelOptions(
            name='membershipplanfeatures',
            options={'verbose_name': 'خصائص العضوية', 'verbose_name_plural': 'خصائص العضويات'},
        ),
        migrations.AlterModelOptions(
            name='membershipplans',
            options={'verbose_name': 'عضوية', 'verbose_name_plural': 'العضويات'},
        ),
        migrations.AlterModelOptions(
            name='workingoaches',
            options={'verbose_name': 'مدرب', 'verbose_name_plural': 'المدربين'},
        ),
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الحجز')),
                ('booking_start_time', models.TimeField(verbose_name='وقت الحجز')),
                ('time_flag', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1, verbose_name='مدة الحجز')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club.facility', verbose_name='المرفق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز المرفق',
                'verbose_name_plural': 'حجوزات المرافق',
            },
        ),
        migrations.CreateModel(
            name='FacilityServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='club.facility', verbose_name='الخدمات')),
            ],
            options={
                'verbose_name': 'خدمة المرفق',
                'verbose_name_plural': 'خدمات المرافق',
            },
        ),
    ]
