# Generated by Django 5.2 on 2026-02-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_facility_alter_club_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitybooking',
            name='user',
        ),
    ]
